In [1]:
import numpy as np

In [2]:
np.absolute(-83274)

83274

In [3]:
#Few important functions

In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
a.shape

(5,)

In [8]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
b.shape

(2, 4)

In [11]:
b.T #Transpose of array b

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [13]:
np.dot(b, b.T) #Dot Product of two arrays

array([[ 30,  70],
       [ 70, 174]])

In [14]:
np.random.randint(60, 100, 10)

array([83, 64, 92, 69, 73, 75, 70, 80, 60, 73])

In [19]:
matrix = np.random.randint(60, 100, (5, 5))

In [20]:
print(matrix)

[[96 84 98 81 96]
 [60 85 77 61 87]
 [78 77 77 69 99]
 [67 98 73 72 99]
 [65 96 87 89 86]]


In [21]:
np.max(matrix)

99

In [22]:
np.min(matrix)

60

In [25]:
a = np.random.randint(0, 100, 7)

In [27]:
print(a)

[58 44 59 15 98 88 42]


In [28]:
np.argmin(a)

3

In [29]:
np.unique(a)

array([15, 42, 44, 58, 59, 88, 98])

In [30]:
np.unique(a, return_counts=True)

(array([15, 42, 44, 58, 59, 88, 98]), array([1, 1, 1, 1, 1, 1, 1]))

In [31]:
#Program to find out the number with the highest frequency in the array

In [32]:
b = np.unique(a, return_counts=True)

In [33]:
print(b)

(array([15, 42, 44, 58, 59, 88, 98]), array([1, 1, 1, 1, 1, 1, 1]))


In [35]:
idx = np.argmax(b[1]) #index with the highest frequency
ele = b[0][idx]
print(ele)

15


In [37]:
#Slicing Arrays
matrix

array([[96, 84, 98, 81, 96],
       [60, 85, 77, 61, 87],
       [78, 77, 77, 69, 99],
       [67, 98, 73, 72, 99],
       [65, 96, 87, 89, 86]])

In [38]:
sliced_arr = matrix[ 2:4, 1:3]

In [39]:
print(sliced_arr)

[[77 77]
 [98 73]]
